version: '3.8'

services:
  backend:
    build:
      context: ./        # Path to the Dockerfile for the backend
      dockerfile: Dockerfile    # Dockerfile name if not 'Dockerfile'
      args:
        - REACT_APP_BACKEND_URL=http://localhost:7000
        - MONGO_URL=mongodb+srv://agagmahmoud:xGiowF7dffBIZmPa@cluster0.xrrtozz.mongodb.net/?retryWrites=true&w=majority
        - JWT_SECRET=BC5kVNZjOF
        - JWT_LIFETIME=1d
        - API_KEY=j1SvC0/dlV9huEqfruyNRA==iWtoDdyERSYTsHXN
    ports:
      - "7000:7000"             # Expose backend's port 3000
    restart: always             # Restart policy
    environment:
      - PORT=7000